### ISSUE TITLE
PCN use emd：In  module.py  assert(n == m)，return AssertionError

### ISSUE THREAD

**Issue by zhaoxiao64** [paul007pl/MVP_Benchmark#28]

**Comment by zhaoxiao64** [comment]
Traceback (most recent call last):
  File "/home/zhao/doc/MVP_Benchmark-main/completion/train.py", line 219, in <module>
    train()
  File "/home/zhao/doc/MVP_Benchmark-main/completion/train.py", line 140, in train
    out2, loss2, net_loss = net(inputs, gt, alpha=alpha)
  File "/home/zhao/anaconda3/envs/mvp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhao/anaconda3/envs/mvp/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhao/anaconda3/envs/mvp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhao/doc/MVP_Benchmark-main/completion/models/pcn.py", line 96, in forward
    loss1 = calc_emd(out1, gt)
  File "/home/zhao/doc/MVP_Benchmark-main/completion/model_utils.py", line 83, in calc_emd
    dist, _ = emd_loss(output, gt, eps, iterations)
  File "/home/zhao/anaconda3/envs/mvp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "../utils/metrics/EMD/emd_module.py", line 88, in forward
    return emdFunction.apply(input1, input2, eps, iters)
  File "../utils/metrics/EMD/emd_module.py", line 47, in forward
    assert(n == m)
AssertionError

进程已结束,退出代码1

**Comment by paul007pl** [comment]
EMD loss requires the "input point cloud" and the "GT point cloud" to have the same number of points.
You may check the emd loss here:
http://robotics.stanford.edu/~rubner/papers/rubnerIjcv00.pdf
